### ISSUE TITLE
Fails to build with RedistMaker

### ISSUE THREAD

**Issue by willCode4Beer** [OpenNI/OpenNI#26]
Output:

./RedistMaker 

---
-   PrimeSense OpenNI Redist    *
-     2011-07-10 14:39:19       *
  *********************************
- Taking version...
  version is 1.1.0.39
- Building OpenNI...
  ../../../../../Samples/NiViewer/Device.cpp: In function ‘XnStatus openDeviceFromXmlWithChoice(const char_, xn::EnumerationErrors&)’:
  ../../../../../Samples/NiViewer/Device.cpp:252:22: warning: ignoring return value of ‘int scanf(const char_, ...)’, declared with attribute warn_unused_result
  error CS0006: cannot find metadata file `System.Windows.Forms.dll'
  make[1]: *** [../../../Bin/Release/SimpleViewer.net.exe] Error 1
  make: *** [Samples/SimpleViewer.net] Error 2
  make: Leaving directory`/home/davisp/Kinect/OpenNI/Platform/Linux-x86/Build'

Building Failed!!

**Comment by OpenNI** [comment]
You need to install the complete mono framework as stated in the Readme.
It's not really optional at the moment. as stated.
This is fixed in the upcoming OpenNI 1.4 where you can skip the .net wrapper.
Ziv.

**Comment by chaiein** [comment]
---
-   PrimeSense OpenNI Redist    *
-     2016-02-15 18:18:52       *
  *********************************

Target: Linux-x86
Version: 1.5.7.10

../../../../../Samples/NiViewer/Device.cpp: In function ‘XnStatus openDeviceFromXmlWithChoice(const char_, xn::EnumerationErrors&)’:
../../../../../Samples/NiViewer/Device.cpp:251:22: warning: ignoring return value of ‘int scanf(const char_, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%d", &chosen);
                      ^
../../../../../Samples/SimpleViewer.net/MainWindow.cs(175,22): warning CS0414: The private field `SimpleViewer.net.MainWindow.scriptNode' is assigned but its value is never used
../../../../../Samples/UserTracker.net/MainWindow.cs(385,22): warning CS0414: The private field`UserTracker.net.MainWindow.scriptNode' is assigned but its value is never used
- Creating Doxygen...
  Warning: Tag `SYMBOL_CACHE_SIZE' at line 330 of file Doxyfile has become obsolete.
  To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  Warning: Tag`SHOW_DIRECTORIES' at line 539 of file Doxyfile has become obsolete.
  To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  Warning: Tag `HTML_ALIGN_MEMBERS' at line 964 of file Doxyfile has become obsolete.
  To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  Warning: Tag`USE_INLINE_TREES' at line 1151 of file Doxyfile has become obsolete.
  To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
  Error: When enabling GENERATE_HTMLHELP the tree view (GENERATE_TREEVIEW) should be disabled. I'll do it for you.
  Warning: doxygen no longer ships with the FreeSans font.
  You may want to clear or change DOT_FONTNAME.
  Otherwise you run the risk that the wrong font is being used for dot generated graphs.
  sh: 1: C:\Program Files\HTML Help Workshop\hhc.exe: not found
  error: failed to run html help compiler on index.hhp
- Creating Redist Dir...
- Copying files to redist dir...
  Samples: ['NiBackRecorder', 'NiSampleModule', 'SimpleRead.net', 'NiUserSelection', 'UserTracker.net', 'UserTracker.java', 'NiSimpleCreate', 'SimpleRead.java', 'NiViewer', 'NiSkeletonBenchmark', 'NiConvertXToONI', 'NiSimpleViewer', 'NiSimpleRead', 'SimpleViewer.net', 'NiRecordSynthetic', 'SimpleViewer.java', 'NiSimpleSkeleton', 'NiHandTracker', 'NiAudioSample', 'NiUserTracker', 'NiCRead']
- Removing Read Only Attributes...
- Fixing Files...
- Creating Makefile...
- Copying install script...
- Building Samples in release configuration......
  ./MainWindow.cs(385,22): warning CS0414: The private field `UserTracker.net.MainWindow.scriptNode' is assigned but its value is never used
  ./MainWindow.cs(175,22): warning CS0414: The private field`SimpleViewer.net.MainWindow.scriptNode' is assigned but its value is never used
  Device.cpp: In function ‘XnStatus openDeviceFromXmlWithChoice(const char_, xn::EnumerationErrors&)’:
  Device.cpp:251:22: warning: ignoring return value of ‘int scanf(const char_, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%d", &chosen);
                      ^
- Building Samples in debug configuration......
  ./MainWindow.cs(385,22): warning CS0414: The private field `UserTracker.net.MainWindow.scriptNode' is assigned but its value is never used
  ./MainWindow.cs(175,22): warning CS0414: The private field`SimpleViewer.net.MainWindow.scriptNode' is assigned but its value is never used
- Creating tar......
- Redist OpenNi Ended.   !!

unable to find the OpenNi-Bin-Dev-Linux-x64-v1.5.2.23 to proceed further. How to resolve this error?

**Comment by Dhagash4** [comment]
I am using Ubuntu 16.04 and ros kinectand I am getting the following ./Redistmaker while building the OpenNI package
I am following the tutorials of the link given below:
http://wiki.ros.org/Robots/evarobot/Tutorials/indigo/Kinect

The following is the error:

> 
*********************************
*   PrimeSense OpenNI Redist    *
*     2017-09-29 18:07:30       *
*********************************

Target: Linux-x64
Version: 1.5.4.0
Num of compile jobs: 8

* Building OpenNI...
../../../../Source/OpenNI/XnRecorderImpl.cpp: In constructor ‘xn::RecorderImpl::RecorderImpl()’:
../../../../Source/OpenNI/XnRecorderImpl.cpp:51:18: warning: converting to non-pointer type ‘XN_FILE_HANDLE {aka int}’ from NULL [-Wconversion-null]
  m_hRecorder(NULL)
                  ^
../../../../Source/OpenNI/XnProfiling.cpp: In function ‘void* xnProfilingThread(XN_THREAD_PARAM)’:
../../../../Source/OpenNI/XnProfiling.cpp:90:168: warning: field width specifier ‘*’ expects argument of type ‘int’, but argument 3 has type ‘XnSizeT {aka long unsigned int}’ [-Wformat=]
   nReportChars += sprintf(csReport + nReportChars, "%-*s %-5s %-6s %-9s %-7s\n", g_ProfilingData.nMaxSectionName, "TaskName", "Times", "% Time", "TotalTime", "AvgTime");
                                                                                                                                                                        ^
../../../../Source/OpenNI/XnProfiling.cpp:91:168: warning: field width specifier ‘*’ expects argument of type ‘int’, but argument 3 has type ‘XnSizeT {aka long unsigned int}’ [-Wformat=]
   nReportChars += sprintf(csReport + nReportChars, "%-*s %-5s %-6s %-9s %-7s\n", g_ProfilingData.nMaxSectionName, "========", "=====", "======", "=========", "=======");
                                                                                                                                                                        ^
../../../../Source/OpenNI/XnProfiling.cpp:108:95: warning: field width specifier ‘*’ expects argument of type ‘int’, but argument 3 has type ‘XnSizeT {aka long unsigned int}’ [-Wformat=]
     pSection->csName, pSection->nTimesExecuted, dCPUPercentage, pSection->nTotalTime, nAvgTime);
                                                                                               ^
../../../../Source/OpenNI/XnProfiling.cpp:121:90: warning: field width specifier ‘*’ expects argument of type ‘int’, but argument 3 has type ‘XnSizeT {aka long unsigned int}’ [-Wformat=]
    g_ProfilingData.nMaxSectionName, "*** Total ***", "-", dCPUPercentage, nTotalTime, "-");
                                                                                          ^
../../../../Source/OpenNI/XnPlayerImpl.cpp: In constructor ‘xn::PlayerImpl::PlayerImpl()’:
../../../../Source/OpenNI/XnPlayerImpl.cpp:71:33: warning: converting to non-pointer type ‘XN_FILE_HANDLE {aka int}’ from NULL [-Wconversion-null]
  m_bPlaybackThreadShutdown(FALSE)
                                 ^
/bin/sh: 1: javac: not found
make[1]: *** [../../../Bin/x64-Release/org.OpenNI.jar] Error 127
make: *** [Wrappers/OpenNI.java] Error 2
make: *** Waiting for unfinished jobs....
../../../../../Samples/NiViewer/Device.cpp: In function ‘XnStatus openDeviceFromXmlWithChoice(const char*, xn::EnumerationErrors&)’:
../../../../../Samples/NiViewer/Device.cpp:252:22: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%d", &chosen);
                      ^
failed to execute: make  -j8 -C /home/dhagash/OpenNI/Platform/Linux/CreateRedist/../Build > /home/dhagash/OpenNI/Platform/Linux/CreateRedist/Output/BuildOpenNI.txt
Building Failed!

Anyone please help

**Comment by welkerCode** [comment]
Dhagash4, did you ever figure out what was the issue?  I get a similar error when trying to install on Ubuntu 16.04.  Mine says:

In file included from ../../../../../Samples/NiViewer/glh/glh_obs.h:62:0,
                 from ../../../../../Samples/NiViewer/NiViewer.cpp:63:
../../../../../Samples/NiViewer/glh/glh_linear.h:77:47: note:   mismatched types ‘const _CharT*’ and ‘std::error_code’
 #define     GLH_EPSILON         GLH_REAL(10e-6)
                                               ^
make[1]: *** [x64-Release/NiViewer.o] Error 1
make: *** [Samples/NiViewer] Error 2
make: *** Waiting for unfinished jobs....
failed to execute: make  -j16 -C /home/taylorwelker/OpenNI/Platform/Linux/CreateRedist/../Build > /home/taylorwelker/OpenNI/Platform/Linux/CreateRedist/Output/BuildOpenNI.txt
Building Failed!

**Comment by shiv248** [comment]
> Dhagash4, did you ever figure out what was the issue? I get a similar error when trying to install on Ubuntu 16.04. Mine says:
> 
> In file included from ../../../../../Samples/NiViewer/glh/glh_obs.h:62:0,
> from ../../../../../Samples/NiViewer/NiViewer.cpp:63:
> ../../../../../Samples/NiViewer/glh/glh_linear.h:77:47: note: mismatched types ‘const _CharT*’ and ‘std::error_code’
> #define GLH_EPSILON GLH_REAL(10e-6)
> ^
> make[1]: *** [x64-Release/NiViewer.o] Error 1
> make: *** [Samples/NiViewer] Error 2
> make: *** Waiting for unfinished jobs....
> failed to execute: make -j16 -C /home/taylorwelker/OpenNI/Platform/Linux/CreateRedist/../Build > /home/taylorwelker/OpenNI/Platform/Linux/CreateRedist/Output/BuildOpenNI.txt
> Building Failed!

I have the same exact error as this, did you find a fix?

**Comment by ghost** [comment]
Hi Shiv248,  did you resolved the issue you mentioned? I got the same when trying to install on pop os.

In file included from ../../../../../Samples/NiViewer/glh/glh_obs.h:62:0,
                 from ../../../../../Samples/NiViewer/NiViewer.cpp:63:
../../../../../Samples/NiViewer/glh/glh_linear.h:77:47: note:   mismatched types ‘const _CharT*’ and ‘std::error_code’
 #define     GLH_EPSILON         GLH_REAL(10e-6)
                                               ^
make[1]: *** [x64-Release/NiViewer.o] Error 1
make: *** [Samples/NiViewer] Error 2
make: *** Waiting for unfinished jobs....
failed to execute: make  -j24 -C /home/harish/Kinect/OpenNI/Platform/Linux/CreateRedist/../Build > /home/harish/Kinect/OpenNI/Platform/Linux/CreateRedist/Output/BuildOpenNI.txt
Building Failed!

Any suggestions to fix this issue please..

**Comment by apostrophedottilde** [comment]
charishnaidu I get exactly the same error as you. Did you ever figure out how to solve this?

**Comment by thisisaggarwal** [comment]
I'm getting the similar error. It's in the file attached. Can someone help me out?
[kinect_error.txt](https://github.com/OpenNI/OpenNI/files/3231850/kinect_error.txt)
[kinect_error.txt](https://github.com/OpenNI/OpenNI/files/3231851/kinect_error.txt)

**Comment by Akhil-Gurram** [comment]
I am also facing the same issue. Can you please let us know if anyone of you (@thisisaggarwal, @apostrophedottilde, @charishnaidu, @shiv248, @welkerCode, @Dhagash4 ) has known how to fix it?
 
Thanks in advance.

**Comment by ghost** [comment]
I resolved this issue by installing an older version of GCC on Ubuntu 18.04.

https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version

I ended up with gcc-4.8, gcc-6 and gcc-7 in sudo update-alternatives --config gcc, chose 4.8 and rebuilt successfully.

**Comment by Dumisanik** [comment]
What I did on Ubuntu 18.04:

1. Install Mono - the opensource .Net implemenation
`sudo apt-get install mono-complete`

2. You need to build the code with an older gcc and g++
```
sudo apt install gcc-4.8 g++-4.8
sudo apt install clang-3.8 clang-3.9 clang-4.0
```

3. Make gcc  4.8 and g++ 4.8 your default compilers. You can revert this by setting a higher priority value for gcc-7 and g++-7
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
```

4. Add `alias clang++="clang++-3.5" `to your .bashrc file in your home directory. _Be careful not to replace everything_
`echo "alias clang++=\"clang++-3.5\"" >> .bashrc`   

export to your termina: 
`export CXX=clang++ yaourt -S openni`
