### ISSUE TITLE
hi everybody

### ISSUE THREAD

**Issue by xhava** [OpenNI/OpenNI#85]
hi i have tried to install openni in fedora, ubuntu debian windows but it really does not work , someone could help m a litle bit. maybe someone knows some video on youtube or something like that... thanks

**Comment by eddiecohen** [comment]
I really recommend switching to OpenNI 2.x (https://github.com/OpenNI/OpenNI2). You can also get support at the website: www.openni.org. There's a forum there full of information.

May I also suggest elaborating a bit more, other than "does not work". What sensor are you using (Kinect/ASUS/other)? What happens when you try to run one of the samples?
